### ISSUE TITLE
Building with last crystal version

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/shards#100]
Hi,

I'm building a `crystal` (**0.15.0**) package for **debian**.

I want to include `shards` in this package.

`Shards` actually need garbage collector to be linked in file **libgc.so.1**, whereas `crystal` **bulding** need to have GC linked in **libgc.so**.

Is this difference wanted ?

Regards,

**Comment by ysbaddaden** [comment]
Nope. Linking GC is Crystal's doing, and should behave the same than compiling Crystal itself.
