### ISSUE TITLE
Tag/version validation

### ISSUE THREAD

**Issue by jhass** [crystal-lang/shards#106]
Following https://github.com/will/crystal-pg/issues/41 I was thinking, maybe shards should refuse to install (during `shards install`) when after the `git checkout $version` the `version` field in the `shard.yml` doesn't match the earlier `$version`? That way a shard that has a mismatch there would be unusable for that version. The validation would only happen for dependencies where the `version` field in the `dependencies` section of the current project is specified of course.

**Comment by ysbaddaden** [comment]
Maybe. Thus sounds harsh but maybe its for the best.

It still works though, and the correct refs is installed. Just a mismatch in the spec and the tag. 

Maybe this outlines a problem: we must sync the version. I thought about skipping the version in the spec, and only use tags, but then we'd lose version information in branches...

**Comment by jhass** [comment]
> I thought about skipping the version in the spec, and only use tags, but then we'd lose version information in branches

For git checkouts we could still recover it from `git describe`, if there's a tag yet at all. But at least for `path` dependency it would be lost, yeah.

**Comment by straight-shoota** [comment]
In #341 we agreed to only issue a warning in case git tag and SPEC version mismatch. This has already been merged.
