### ISSUE TITLE
New project, parse error expected scalar but was sequence start

### ISSUE THREAD

**Issue by boatmon0** [crystal-lang/shards#112]
I'm new to crystal, building my first project. I am operating on debian 8.5, crystal version 0.18.7.

I built the project using "crystal init lib harvest"

 I just tried shards, added crystal-lang/crystal-db to a dependency and ran shards update.  I get the error "shard.yml:0: Shards::ParseError: expected SCALAR but was SEQUENCE_START at 0:0"

I get the error at "name: harvest".  The first line of my yml file.  

I'm sure it's something a noob encounters.  Do I need to make a directory?  Is this some kind of git error? Is there something that I have not installed?  What do you need to know to help?

Lets see, I installed crystal, ran a couple of little test programs, decided that I needed a database, installed sqlite3  tested that the install went well.  Then I added the dependencies in the shard.yml and ran shard, that is when everything quit.  

Thanks for any help.
Eugene

**Comment by asterite** [comment]
Can you show the contents of your `shard.yml`? The error means the yaml file is malformed.

**Comment by boatmon0** [comment]
Thanks for responding.  Here is my shard.yml file.

name: harvest
version: 0.1.0

authors:
  - [Eugene Jones] <[ejones@connect4business.com]>

license: MIT

dependencies:
  db:
    github: crystal-lang/crystal-db
  sqlite3:
    github: crystal-lang/crystal-sqlite3

**Comment by boatmon0** [comment]
I found the problem, at least the first problem.  Removed brackets around my name and email address.

**Comment by ysbaddaden** [comment]
Using a Shards binary built using an older Crystal compiler (built on May 5) I get the correct message, reporting an error on `4:4`:

```
in /tmp/harvest/shard.yml:4: Shards::ParseError: expected SCALAR but was SEQUENCE_START at 4:4

  1.
  2. authors:
  3.   - [Eugene Jones] <[ejones@connect4business.com]>
```

But if I build Shards now (with Crystal 0.18.7) the error message reports the `0:0` position instead...

**Comment by ysbaddaden** [comment]
@asterite the problem comes from https://github.com/crystal-lang/crystal/commit/9600cdbe64e9a456fbec104e4d6d3823d2362322 and more specifically [this change](https://github.com/crystal-lang/crystal/commit/9600cdbe64e9a456fbec104e4d6d3823d2362322#diff-2e2c8ae020619553483bd0c67fcf50b6L194) in `YAML::PullParser`:

```diff
-    raise ParseException.new(msg, line_number, column_number)
+    raise ParseException.new(msg, problem_line_number, problem_column_number)
```

**Comment by asterite** [comment]
@ysbaddaden Thanks for pointing this out. I think I fixed it here: https://github.com/crystal-lang/crystal/commit/db70dee490f9b367f03bacd6caf6e5d9010c71dc

(not sure about that change, but libyaml doesn't have docs about the internal parser structure)

**Comment by ysbaddaden** [comment]
Great!
