### ISSUE TITLE
Arbitrary dependency groups

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/shards#118]
> I could see adding the ability to define arbitrary groups as being useful. Something akin to a Gemfile in ruby. Then a makefile etc.. could build the executable the appropriate groups enabled. I only gave the shards yml SPEC a cursory glance, but it appears to only allow dependencies and development_dependencies. I could see the possible need for test, production etc... groups as well, but there is no need to limit it to just those. It would be neat if any type of group could be named in the shards yml. precompile, assets, docker etc.. There are many possibilities.
> 
> By @hattwj in https://github.com/crystal-lang/shards/issues/110#issuecomment-246125177

**Comment by ysbaddaden** [comment]
I'm not sure we do need arbitrary groups in dependencies.

In contrast to Ruby where dependencies are required at runtime, we only need them at compile time, so we build a binary and then distribute it. I believe the context where the application will run doesn't change the dependencies it requires for compiled, especially since we can't selectively require a dependency or not. This kind of makes a `production` group useless, and by extension any particular group.

The one exception is development, including testing, hence the `development_dependencies` this can be a little different from strictly building a binary; thought it's merely bundling test shards (at least for me). I never felt the need to separate `development` and `test` (yet).

I'm willing to hear actual use cases and needs before considering this.

**Comment by Xosmond** [comment]
@ysbaddaden Do you know how to declare a production dependencies block? I can find any doc about it, because I need a shard on local machine and other on server.

**Comment by ysbaddaden** [comment]
What do you mean?

**Comment by Xosmond** [comment]
@ysbaddaden  Something like:
```yaml
dependencies:
  development:
    kemal:
      github: kemalcr/kemal
  production:
    kemal:
      github: myself/kemal
```

**Comment by ysbaddaden** [comment]
That's not possible, and would break reproducible builds across computers. You must use one unique source for a shard for all environments.

**Comment by Xosmond** [comment]
@ysbaddaden yes but sometimes c bindings are problematic, well, thanks.

**Comment by ysbaddaden** [comment]
Closing as wontfix for the foreseeable future.
