### ISSUE TITLE
docs for SPEC

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#122]
I was going to do a PR for this, but I wasn't really sure the best way to write it. 

I had some confusion earlier when specifying a github repo without any additional attributes, and it wasn't installing the shard I expected. I added a specific version, it said it couldn't find it. I wasn't aware that it looks at the latest releases for that version and I had to specify `branch: master` for it to pull the latest on that branch. 

I think having some docs explaining this might help a lot of new people coming to crystal.

**Comment by dannyshafer** [comment]
Does this one answer your question? Or should there be more? https://github.com/crystal-lang/shards/blob/master/SPEC.md

**Comment by ysbaddaden** [comment]
Yes, SPEC is fully documented but commands are not (thought there is a [preliminary man page](https://github.com/crystal-lang/shards/blob/master/src/man/shards.1)). SPEC details the `shard.yml` file format, expected values in the file, and so on, but it doesn't explain how commands behave.

For example `install` and `update` default to *released* version numbers (as git tags), not to branches (despite using git).

**Comment by ysbaddaden** [comment]
Related to #11

**Comment by jwoertink** [comment]
Yeah, these docs have come along further since I asked this question. I haven't tested to see if shards acts the same way, but the docs do mention `When missing, Shards will install the HEAD refs.` related to not having a second argument for github. At the time of the question, that wasn't correct though. I think this can be closed out.

**Comment by ysbaddaden** [comment]
Oh, the wording is (was?) confusing: it's supposed to mean "when a shard doesn't have any release, then the HEAD refs will be selected" and not understood as "when `version:` is missing it will default to the HEAD refs" because it actually defaults to `*` (any *version number*).
