### ISSUE TITLE
Integrate new search path algorithm

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/shards#123]
We must follow the search patch changes of https://github.com/crystal-lang/crystal/pull/2788. This is a **breaking change**; projects will have to run `rm -rf libs; shards install` in their projects for the new dependencies to be installed correctly.
- [x] install dependencies in `lib` instead of `libs`;
- [x] install dependencies as a whole (not merely the `src` folder).

**Comment by ysbaddaden** [comment]
This is blocking #95 (and possibly #110) from being implemented, since the `bin` folder of dependencies isn't available.

**Comment by RX14** [comment]
Should shards detect the old `libs` format and delete it before install? Have a marker file? Is that too much work for little gain?

**Comment by ysbaddaden** [comment]
Maybe print a message? Maybe have `shards prune` remove it? Or ask for permission? I'm never comfortable deleting files on someone's computer...

**Comment by RX14** [comment]
Maybe print a message saying it's in the old format and must be removed, then exit.
