### ISSUE TITLE
request: remove shard.lock at exit

### ISSUE THREAD

**Issue by rdp** [crystal-lang/shards#130]
Might be nice to cleanup the file just so it doesn't stick around:

```
$ shards install
Updating xxx
Using xxx
$ git status
...
Untracked files:
  (use "git add <file>..." to include in what will be committed)

    shard.lock

```

**Comment by RX14** [comment]
`shard.lock` isn't a temporary file, it's used to lock your dependencies to specific versions when you specify dependency ranges such as `~> 0.5.3`. Like `Gemfile.lock` in ruby, you should commit the file to git in an application, but not in a library.

**Comment by rdp** [comment]
oh wow that is super confusing to non rubyists like myself.  Perhaps it
could be named something more descriptive like... shard.versions or
something [?]

**Comment by RX14** [comment]
There should at least be some documentation about it.

**Comment by ysbaddaden** [comment]
Commands are documented in the man page:
https://github.com/crystal-lang/shards/blob/master/src/man/shards.1

The lock mechanism is explained there. I agree this is kinda buried, and we should have a `shards help` command that could render the man page for example (I'll like to avoid duplicating documentation).

**Comment by rdp** [comment]
maybe when the file is first created a helpful message could be output to
console like "creating shard.lock file to track current git commits" or
something... :)

**Comment by Sija** [comment]
This issue can be closed now (and should be, but the commit message contained misspelled "closes" keyword ;)).
