### ISSUE TITLE
different update on linux and mac

### ISSUE THREAD

**Issue by kostya** [crystal-lang/shards#131]
`shards update` on linux always replace all revisions to HEAD (in shard.lock),
update on mac replace all revisions to some SHA.
so very often i need to commit this changes in the repo :)

git on linux

```
git version 1.9.1
```

on mac

```
git version 2.9.3
```

``` diff
-    version: HEAD
+    commit: 8c839bf3df5963ccdc36f96d4ba9b4d37c1aa409
```

**Comment by ysbaddaden** [comment]
I think you're right about the Git version difference. I see no reason why linux/darwin would behave differently :/

**Comment by straight-shoota** [comment]
This would probably be fixed when using libgit instead of git CLI (#129)

**Comment by kostya** [comment]
i cant check it right now

**Comment by ysbaddaden** [comment]
Actually, the locked version should always be the commit sha1 when targeting a refs. I can't reproduce seeing `version: HEAD` under Linux with Git 1.9.1 (Ubuntu 14.04), which is expected because HEAD is a Git refs, not a valid shard version.
