### ISSUE TITLE
crystal deps should check that dependencies already checkouted

### ISSUE THREAD

**Issue by kostya** [crystal-lang/shards#133]
i am running `crystal deps` on the server (in the shared path) when finalizing deploy and before compiling binary. Often dependencies not changed, but it tries to fetch all dependencies every time, so deploy is very slow. I also trying to use this command `crystal deps check || crystal deps --production`, but it always satisfied even, when dependency was updated.

**Comment by ysbaddaden** [comment]
`shards check` will fail when dependencies changed in `shard.lock` or when the version requirements don't match the installed shards. If `shard.lock` isn't commited and installed shards match requirements in `shard.yml` then it considers installed shards are compatible.

One can commit `shard.lock` or using stricter version requirements in `shard.yml` to solve the `shards check || shards install` command.
