### ISSUE TITLE
Drop support for empty and legacy dependencies (Projectfile)

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/shards#142]
We should print a warning in a patch release when we generate a `shard.yml` file on-the-fly when a project doesn't only has a `Projectfile` (legacy) or nothing at all that support for these cases will be removed in the next MINOR release, and one should create / bug the author that they must define a `shard.yml` file, now.

Shards is mature enough!

**Comment by straight-shoota** [comment]
I'm pretty sure support for Projectfile can now be dropped right away. I don't think there's any repository still using that. I couldn't even find any documentation on it.

**Comment by ysbaddaden** [comment]
Yes, it's 2018, it can be fully removed.

**Comment by molnarmark** [comment]
@ysbaddaden Is a PR needed for this? If so, I can do it when I get home.

**Comment by ysbaddaden** [comment]
There is some code to remove in a few place, yes. Please open a PR if you have the time.

**Comment by molnarmark** [comment]
In some cases, it is used as a fallback. Here is a snippet:
```crystal
    def read_spec(version = "*")
      update_local_cache
      refs = git_refs(version)

      if file_exists?(refs, SPEC_FILENAME)
        capture("git show #{refs}:#{SPEC_FILENAME}")
      else
        if file_exists?(refs, "Projectfile")
          contents = capture("git show #{refs}:Projectfile")
          dependencies = parse_legacy_projectfile_to_yaml(contents)
        end

        version = version_at(refs) || DEFAULT_VERSION
        "name: #{dependency.name}\nversion: #{version}\n#{dependencies}"
      end
    end
```

In that case, should it throw some type of error or something?
