### ISSUE TITLE
`shards check` should exit zero if no shards.lock exists and no dependencies are required

### ISSUE THREAD

**Issue by bacongobbler** [crystal-lang/shards#145]
Hey everyone! Just playing around with Crystal a bit and I'm starting to write a [Heroku buildpack](https://devcenter.heroku.com/articles/buildpacks) for Crystal. Just starting to get my feet wet with shards. Cool project!

Given a sample application such as https://github.com/fishworks/example-crystal with no external dependencies (just the standard library), I would expect that `shards check` would consider it a valid application given that `shards install` will not produce a shard.lock file. Is `shards check` the proper way to "lint" a project for correctness?

This was tested with crystal 0.20.1, installed via homebrew.

**Comment by ysbaddaden** [comment]
Indeed.
