### ISSUE TITLE
RFC: `shards version` to obtain current version defined in shard.yml

### ISSUE THREAD

**Issue by luislavena** [crystal-lang/shards#147]
For some libraries I define `VERSION` constant to help me obtain version information at runtime of the components used by other tools.

The issue I found is that on every release, I have to update `version.cr`, `shard.yml` and match with the tag used in Git.

Was thinking that could be possible to introduce a way to read `shard.yml` (provided by shards itself) so a macro can be used to generate the `VERSION` constant.
 
Not sure about the name of the command, but if approved I can send a pull request to introduce it.

Thank you. :heart: :heart: :heart:

**Comment by Sija** [comment]
Sth like this? :)

```cr
module Foo
  VERSION = begin
    YAML.parse(File.read(File.join(__DIR__, "../..", "shard.yml")))["version"].as_s
  end
end
```

**Comment by luislavena** [comment]
That needs to be read at compile time, if not it will depend on shard.yml
being present when executed, which is why suggested something that can be
used with macros.

Sorry for top posting, sent from mobile.

**Comment by mverzilli** [comment]
I think it's a valuable addition. @ysbaddaden, would you be against adding this?

**Comment by ysbaddaden** [comment]
No strong opinion. That would allow something like:

```crystal
module Wonderful
  VERSION = {{ `shards version` }}
end
```

Thought, how to be sure that the folder the command is run is the one with the `shard.yml` file? Won't it usually be the main project's folder? This is fine for the project, but what about libraries? This is the only issue I foresee with this solution.

**Comment by luislavena** [comment]
Thank you @ysbaddaden for taking the time to look into this.

Really didn't put a lot of thought into the idea, which got exposed by the issue you described for libs (and what could be a problem).

I think that `shards version __DIR__` is a nice a nice solution!

Will you accept such contribution? Will try to find some time to hack on this during the weekend.

Thank you.

:heart: :heart: :heart:

**Comment by ysbaddaden** [comment]
Please do :heart:

**Comment by luislavena** [comment]
Done!, submitted #148.

Cheers! :smile_cat:
