### ISSUE TITLE
`shards install` is not working

### ISSUE THREAD

**Issue by oltmannsdaniel** [crystal-lang/shards#151]
If I want to execute shards install  didn't get any output on Linux. How can I solve that issue?

**Comment by ysbaddaden** [comment]
This happens when a `shard.yml` is present but without `dependencies`.

**Comment by oltmannsdaniel** [comment]
Sorry. It was my mistacke. I put the dependencies under the target point.

**Comment by KCErb** [comment]
Would a PR be welcome to add a debug statement to this effect? This one bit me today and I was surprised that `shards install -v` produced no output. A little "Checking shards.yml `dependencies` key" or "No `dependencies` in shards.yml" in verbose mode would be nice :)

**Comment by bcardiff** [comment]
I think that a "no dependencies nor development_dependencies found" is a good improvement. I would even suggest to have it in non-verbose runs.

Another alternative is to validate the structure of the file. That would catch a missplaced `dependecies` keys.

**Comment by KCErb** [comment]
The above doesn't indicate who closed the issue or why, but after looking at the behavior of the current version on `master` it looks like things were changed so that a `shard.lock` is generated even without the `dependencies` key and so "silent failure" is no longer an issue.

Thanks folks!

**Comment by straight-shoota** [comment]
Yes, this was changed in #453
