### ISSUE TITLE
Add Shards to Libraries.io

### ISSUE THREAD

**Issue by flagello** [crystal-lang/shards#156]
[Libraries.io](https://libraries.io) — [How to](https://github.com/librariesio/libraries.io/blob/master/docs/add-a-package-manager.md
)

[The existing link](https://libraries.io/languages/Crystal) is outdated.

**Comment by ysbaddaden** [comment]
I'm sorry, but I have *no* idea what `libraries.io` is. I glanced at https://docs.libraries.io but that didn't help. Please explain what benefit could be gained, if any.

Futhermore, it's impossible: we don't have a central registry.

**Comment by Sija** [comment]
Some1 already made it – see https://libraries.io/shards & https://crystal-shards-registry.herokuapp.com
