### ISSUE TITLE
How do shards qualify as shards?

### ISSUE THREAD

**Issue by llamicron** [crystal-lang/shards#158]
[crystalshards.xyz](http://crystalshards.xyz/) lists the most recent crystal shards. How does it know what repositories are shards and what aren't? Does it look for a `shard.yml`?

**Comment by bcardiff** [comment]
They filter by language. https://github.com/f/crystalshards/blob/master/app.cr#L28

**Comment by llamicron** [comment]
Ah, I see. Thanks.
