### ISSUE TITLE
Shard require path issue

### ISSUE THREAD

**Issue by eonuonga** [crystal-lang/shards#165]
Currently working on macOS Sierra (10.12).

I installed Crystal earlier today with homebrew and was testing out the [Crystagiri]() gem to make a web crawler. I used 

```bash
$ crystal init app crawl
```

like normal to generate the folder structure added the dependency to `shard.yml` and ran:

```bash
$ crystal deps
$ shards install
```

in /Users/user/Downloads/crystal/crawl, where the folder structure was generated.

My `shard.yml`, `crawl.cr` and `shard.lock` can be seen [here](https://gist.github.com/eonuonga/8fd9fb984ea0cc5307328ec68e00d73b), and `lib/crystagiri` looks like [this](https://image.ibb.co/kpqGMa/Screen_Shot_2017_08_07_at_11_23_44_PM.png). The `crawl.cr` is just requiring the Crystagiri file, but I get the following error when I try to compile `crawl.cr` in terminal:

```bash
$ crystal crawl.cr
Error in crawl.cr:2: while requiring "crystagiri": can't find file 'crystagiri' relative to '/Users/user/Downloads/Crystal/crawl/src'
```

I was having problems with OpenSSL/LibSSL but I fixed those and still get the same problem.

When running `echo $SHARDS_INSTALL_PATH` no path appears, so I'm not sure what's wrong.

There's always the workaround of doing (as suggested by straight-shoota on IRC):

```crystal
require "../lib/crystagiri/src/crystagiri.cr"
```

Which actually works and compiles fine, but I thought I'd raise this issue.

**Comment by RX14** [comment]
@eonuonga You need to be in the root directory with your `shards.yml` in when running the crystal compiler, or it won't work. You might be cd'ed into the `src` directory.

**Comment by ysbaddaden** [comment]
Shards doesn't change how Crystal requires libraries. If Crystal isn't run from the root folder `crawl/` but `crawl/src`, then crystal won't search `crawl/lib` but search the nonexistent `crawl/src/lib`, for example.

**Comment by eonuonga** [comment]
Ahh yes, not sure why I didn't see that, sorry!
