### ISSUE TITLE
"crystal deps", not "shards"

### ISSUE THREAD

**Issue by SolarLune** [crystal-lang/shards#173]
Hey, there. You might want to rearrange the Readme to mention that since shards is part of crystal, you invoke it using `crystal deps`, not `shards` or `crystal shards`. The readme.md does mention this, but still mentions using `shards` after this point. For example:

> Shards is now distributed with Crystal itself (at least in the Homebrew and Debian/Ubuntu packages). You can invoke it with crystal deps.

... And then later,

> Simply run shards install to install your dependencies,

**Comment by asterite** [comment]
I'd like to remove `crystal deps` and just use `shards`.
