### ISSUE TITLE
Shards are not working with Crystal 0.24

### ISSUE THREAD

**Issue by Sija** [crystal-lang/shards#175]
Mainly due to the refactoring of `YAML` implementation in stdlib (https://github.com/crystal-lang/crystal/pull/5007).

**Comment by ysbaddaden** [comment]
Fixed in 11602bcd632e44669572e32e69f8a09a4b424d99, 9a3997ada429c4ad6a8e3b3b1eff4ef34453dbf3 and 11c6fb46972f99d26a03d2cc3305717c34fe0a9b.

**Comment by monouser7dig** [comment]
works now, if some CI could be put in place to test crystal master compatibility in the further that would be...

(I just mean test, not enforce, just test so that failures are at detected automatically)
