### ISSUE TITLE
WebView listing of available shards

### ISSUE THREAD

**Issue by shevegen** [crystal-lang/shards#182]
Hi crystal folks,

Sorry if this has already been discussed before; feel free to close this issue at any moment in time.

Would it be possible to have a listing + descriptions of shards, similar to rubygems.org (I refer to the basic functionality, not the layout or extended stuff)?

In its simplest form, I guess an alphabetical listing may suffice and perhaps a brief entry what the respective shard does. Right now there appears to be only a link to the (github) repo, and I assume this is because there isn't yet code added to view/show the available shards over the www.

Ideally it could become a part of the official homepage one day, e. g. at https://crystal-lang.org/shards or something like that. But I understand that it is not of the highest priority right now, I think.

**Comment by bcardiff** [comment]
Hi @shevegen . There are some listings available at https://crystal-lang.org/community/#shards . Either a curated awesome list or a github listing by language with some additional information.
Both of them are maintained by the community directly.

**Comment by straight-shoota** [comment]
And the `shards` program itself (what this repo is about) doesn't need a central registry like bundler uses rubygems.org, it just fetches the shard metadata directly from a source repository.

**Comment by ysbaddaden** [comment]
Closing. This isn't on our radar for the time being.
