### ISSUE TITLE
Update man pages

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/shards#189]
The man pages for `shards` and `shards.yml` have outdated information (e.g. repository URL). The commands `build`, `init`, `list`, `prune` and `version` are missing, as well as the dependency attribute `gitlab` and attributes `libraries`, `scripts` and `targets`. I've probably missed somthing.

**Comment by lebogan** [comment]
Are man pages supposed to be installed with Crystal? Or, should I clone the source and build locally? I'm on Fedora 27 running Crystal 0.24.2.

Thanks.

**Comment by lebogan** [comment]
I used the instructions for Fedora using dnf.

**Comment by RX14** [comment]
@lebogan which ones? You mean you added a new repo and installed the package? The man pages should be in `/usr/share/man/`, so they should work...

**Comment by straight-shoota** [comment]
The man pages are missing in the deb package, as well.

Judging from https://github.com/crystal-lang/distribution-scripts/blob/master/linux/Dockerfile they're probably not included in any package.

**Comment by RX14** [comment]
Oh, I'm blind, this is about the shards manpage not the crystal one. Yeah that's a bug in crystal-lang/distribution-scripts.

**Comment by straight-shoota** [comment]
This should be fixed by now.
