### ISSUE TITLE
Request: put release dates in the CHANGELOG

### ISSUE THREAD

**Issue by anicholson** [crystal-lang/shards#194]
As the versioning isn't really in sync with `crystal-lang` itself, it's hard to get a gauge of how new a feature is just by looking at which version it came out in.

It would be nice to be able to see "ah, this was introduce in version 0.x.y, which (based on the datestamp) was `z` months ago.

**Comment by ysbaddaden** [comment]
Sure. They're on the [releases](https://github.com/crystal-lang/shards/releases) page thought.
