### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/shards#201]
Hi @ysbaddaden 

`shards install` is a nice tool, but sometimes, when I use many shards the ouput is a bit noisy. I can use the `-q`  (quiet) flag, although, I think would be nice to have a progress bar option like other packages managers does (NPM, Yarn, Hex, gem, pip, etc)

Maybe the "new" progress bar option can be based on [one of these cli util shards](https://github.com/veelenga/awesome-crystal#cli-utils)

WDYT?

**Edit:**

Another nice option is prepend lines like `[07/10] Installing foo` suggested by @RX14 https://github.com/crystal-lang/shards/issues/201#issuecomment-383422019

**Comment by RX14** [comment]
Do you really have that meany shards you need a progress bar already? Shards is a pretty darn quick package manager.

**Comment by faustinoaq** [comment]
> Shards is a pretty darn quick package manager.

@RX14 Yeah, but my connection is pretty slow, (under 1 MB), so, a progress bar can be very helpful

**Comment by RX14** [comment]
I'm not sure how easy it is to make a progressbar for each download, since we'd have to parse git output. We could do progress at the granularity of whole shards but I don't really find that useful. For that case i'd rather just prepend the install lines with something like `[07/10] Installing foo`

**Comment by faustinoaq** [comment]
> For that case i'd rather just prepend the install lines with something like `[07/10] Installing foo`

@RX14 Oh yeah!, That would works :+1:

**Comment by ysbaddaden** [comment]
This isn't possible: Shards doesnt know beforehand how many dependencies there will be to resolve and fetch. It discovers them as it fetches dependencies and parses their `shard.yml`.

Prepending a number will just grow both numbers. A progressbar would do the same, and the bar would jump around. These would confusing and useless.

**Comment by faustinoaq** [comment]
@ysbaddaden Ok, no problem :sweat_smile:
