### ISSUE TITLE
[Future] Broken build from sources with the newest Crystal version

### ISSUE THREAD

**Issue by SlayerShadow** [crystal-lang/shards#203]
Crystal version: `Crystal 0.24.2+336 [6c3fc2b93] (2018-05-05)`

`make` command provides:
1. `in src/package.cr:86: undefined method 'stat' for File:Class`
2. `in src/package.cr:86: undefined method 'ino' for Crystal::System::FileInfo`

Depending on [this commit in Crystal](https://github.com/crystal-lang/crystal/commit/96bcc34afbcf23d50823aaecb0c12b6eed0f8fac), there are no more `stat` and `ino` methods.

For me it fixes situation (in `src/package.cr:86`):
`next if File.stat(destination).ino == File.stat(source).ino` changed to
`next if File.info(destination) == File.info(source)`

After that it compiled and launched successfully, but i'm not sure it's completely correct thing.
Compiled version: `Shards 0.7.2 [df9face] (2018-05-05)`

**Comment by RX14** [comment]
Yes, that is the correct fix. Not sure when we'll be releasing the next version of crystal and so when to merge that change.

**Comment by bcardiff** [comment]
Shards 0.7.2 can be built with either 0.24.2 or crystal head.
The File.stat/ino where added after 0.7.2.

@ysbaddaden I see some nice features in shards not released yet. 

Is there any preference to release a shards 0.8 with crystal 0.25 or to stick with 0.7.2?
Is there any importan information to notice in crystal release if shards is updated?

Note: I left a branch with the proposed changes since I needed them to check

**Comment by ysbaddaden** [comment]
There is mostly a breaking change (global cache) which I haven't tested much, but we can release a 0.8 yes.

**Comment by bcardiff** [comment]
Let's release 0.25.0 with 0.7.2 and avoid having a hiccup in the ci of shards since it requires 0.25.0 to be built. But schedule 0.8.0 for the next one.

**Comment by ysbaddaden** [comment]
Since there is a PR about `File.same?` we should be capable to fix master and release it as `v0.8.0`.

**Comment by bcardiff** [comment]
That's true, it's needs a fix either way.

Let's make sure shards 0.8.0 can compile with 0.24.2 and 0.25.0 then and release 0.8.0.
Otherwise the CI will complain for a while.
