### ISSUE TITLE
Enable author publishing than automatic publishing

### ISSUE THREAD

**Issue by stern0** [crystal-lang/shards#204]
One thing I still don't understand with shards is the automatic publishing of packages. While with most package managers, the author decides to publish their package in the registry shards does it automatically which I think is wrong.

The author must decide whether to make it a module on the registry or not.

**Comment by ysbaddaden** [comment]
You must manually create a version tag and push it to the repository to 'publish' a shard. There is nothing automated here. Please add more details, because we sadly don't follow. Closing until then.

**Comment by straight-shoota** [comment]
> You must manually create a version tag and push it to the repository to 'publish' a shard.

That's not really true. Every git repository can serve as a "published" shard even if it doesn't have any tags.
