### ISSUE TITLE
Targets are not build anymore when a shard is installed as dependency

### ISSUE THREAD

**Issue by olbat** [crystal-lang/shards#220]
It seems that `targets` are not built anymore when a shard is installed as dependency.
Is it intentional ? Am I doing something wrong ?

__To reproduce__

Create a repository to be included as dependency
```
$ git init /tmp/hello
$ mkdir /tmp/hello/src
$ echo 'p "Hello world !"' > /tmp/hello/src/main.cr
$ cat << EOF > /tmp/hello/shard.yml
---
name: hello
version: 0.1.0
executables:
- hello
targets:
  hello:
    main: src/hello.cr
EOF
$ git -C /tmp/hello add -A && git -C /tmp/hello commit -m 'Initial commit'
```

Now create a shard that depends on this repository
```
$ cat << EOF > shard.yml
---
name: project
version: 0.1.0
dependencies:
  hello:
    git: file:///tmp/hello/.git
EOF

$ shards install
Fetching file:///tmp/hello/.git
Using hello (0.1.0 at HEAD)

$ find lib/hello
lib/hello/
lib/hello/shard.yml
lib/hello/src
lib/hello/src/main.cr
```
(_lib/hello/bin/hello_ is missing ...)

__Temporary fix__

Manually build the targets adding `postinstall` entry in the deps' _shard.yml_ file:
```
$ cat <<EOF >> /tmp/hello/shard.yml
scripts:
  postinstall: crystal build -o bin/hello src/main.cr
```

**Comment by ysbaddaden** [comment]
This is by design. Targets are never built when a shard is installed. You must specify the build in a postinstall script if such binaries are meant to be used by the app that installs it.

**Comment by ysbaddaden** [comment]
Note that you can have:
```yaml
targets:
  foo:
    main: src/foo.cr

executables:
  - foo

scripts:
  postinstall: shards build --release
```

**Comment by olbat** [comment]
Oops, ok, thank you for the explanation :)

(BTW, I think in some way it was working like this in the version of shard that was bundled with Crystal 0.24 because I got a piece of software that was depending on it)

**Comment by straight-shoota** [comment]
Maybe you used `path` instead of git resolver. Then the lib folder is just a symlink and will contain the built binary if it's available in the dependencies source directory.

**Comment by olbat** [comment]
Not really, I used the `github` resolver and only a `target` entry.
It was working fine in both a Docker and TravisCI context.

Anyway, I've updated my _shard.yml_ files using a postinstall script as advised by ysbaddaden and it's working like a charm :)
