### ISSUE TITLE
Recommend the usage of SPDX license identifiers in the `license` field

### ISSUE THREAD

**Issue by Calinou** [crystal-lang/shards#221]
The [specification](https://github.com/crystal-lang/shards/blob/master/SPEC.md#license) currently states:

> ### license
>
> An [OSI license](http://opensource.org/) name or an URL to a license file (String, recommended).

It could be a good idea to rely on [SPDX license identifiers](https://spdx.org/licenses/) for common licenses out there, which would make it easier to parse license fields programmatically. This is encouraged by many other package managers already, such as [Cargo](https://doc.rust-lang.org/cargo/reference/manifest.html).

**Comment by ysbaddaden** [comment]
The SPEC should specify a license **identifier** instead of **name**, because this is what we expect, and add some examples, such as Apache-2.0, MIT, BSD-3-clause, ... OSI and SPDX use the same identifiers , so that doesn't really matter and could link to both.

**Comment by RX14** [comment]
@ysbaddaden the SPDX page makes it easier to find the indentifier for a licence, since it's all on one page.

**Comment by ysbaddaden** [comment]
Same for OSI: https://opensource.org/licenses/alphabetical expect that it's not just a list of opensource licenses. We can reference the blunt SPDX table, but I'd still like to keep referencing OSI, for example the https://opensource.org/licenses/category page, which is nicer.

**Comment by RX14** [comment]
@ysbaddaden yeah that page is nice!

**Comment by ysbaddaden** [comment]
I'm not sure how to phrase the SPEC, thought.

**Comment by bcardiff** [comment]
Removing this from milestone 0.10.0. When there is a PR this can be milestoned again.

**Comment by straight-shoota** [comment]
Resolved by #641
