### ISSUE TITLE
Adding a clarification to the shard behavior in case of local copy to avoid surprising behavior

### ISSUE THREAD

**Issue by Zenohate** [crystal-lang/shards#234]
I just noticed `shards install` behavior for local repositories is to make a link to the directory where the repository sits.

This can lead to people deleting their stuff from the `lib/` subfolder and deleting their work likewise.

I advise a warning displayed on linking the repo on `shards install`.

**Comment by straight-shoota** [comment]
This is explicitly mentioned in [SPEC](https://github.com/crystal-lang/shards/blob/master/SPEC.md):

> The library will be linked from the local `path`.

**Comment by ysbaddaden** [comment]
I don't understand. That's the whole point of the path resolve: use the dependency at path.

Using a link also avoids the issue of deleting the linked project's source, since AFAIK an `rm -rf lib` will delete the links themselved, not follow the links and delete the dependency's original files.

**Comment by Zenohate** [comment]
> AFAIK an rm -rf lib will delete the links themselved, not follow the links and delete the dependency's original files

But some IDE like Eclipse and (as I discovered when it happened to me) Visual Studio Code will remove every element of a directory before dropping the directory itself. Also, the behaviour of linking looked extremely surprising as one may expect uniform behaviour between installs of shards of different nature.

Maybe replacing the message for shards that get symlinked from `Installed <shard-name> <version>` to `Linked <shard-name> <version>` would make it less surprising?

If you think so I don't mind making the change myself

**Comment by ysbaddaden** [comment]
That's an IDE bug I think, delete shouldn't follow links, for the very reason of this issue :/

Reproducible installs are impossible with `path`. It really just means "use the lib at path" where the path is deeply tied to your computer, and no version check is done, either.

Maybe we could say Linking instead of Installing but I'm not sure it's that easy.

**Comment by ysbaddaden** [comment]
Or maybe "Using foo (at /path/to/foo)" to mimic installing/using a git commit.

**Comment by Zenohate** [comment]
> to mimic installing/using a git commit.

Well that is exactly the issue, it FEELS like using a thing with a copy behaviour, hence the wording I proposed.

Maybe `Using foo (linked from /path/to/foo)` ?

**Comment by straight-shoota** [comment]
I'd go with `Linked <shard-name> from <path>`. It's precise and unambiguous. Printing a version doesn't make sense because it's only reports the current version. It might as well change in the linked directory without noticing it.

**Comment by Zenohate** [comment]
I can't but agree with that, to me it looks perfectly unambiguous, concise and make it impossible to misunderstand the behaviour
