### ISSUE TITLE
Getting 500 error visiting https://crystalshards.xyz

### ISSUE THREAD

**Issue by jtorreggiani** [crystal-lang/shards#241]
I am receiving a 500 error when visiting https://crystalshards.xyz. Page renders with the following error.
<img width="1280" alt="screen shot 2018-12-01 at 13 04 43" src="https://user-images.githubusercontent.com/4009178/49328487-b9a88380-f569-11e8-8e40-a70397eb6056.png">

Wasn't sure the best place to report the issue.

**Comment by bcardiff** [comment]
Thanks for reporting but crystalshards.xyz is managed by https://github.com/f/crystalshards .
Please do a follow up in that repo so @f can handle it.

**Comment by RX14** [comment]
There's also https://crystalshards.org/ from @jwaldrip which is still working.

**Comment by jtorreggiani** [comment]
Got it @bcardiff, thanks! I will follow up on the other repo. And thank you @RX14 for the heads up about https://crystalshards.org.

**Comment by f** [comment]
Fixed. http://crystalshards.xyz/ Sorry for the problem, won't be repeated.

**Comment by f** [comment]
Also open the issues page which I don't know why closed. https://github.com/f/crystalshards/issues
