### ISSUE TITLE
[SPEC] Add specification for metadata fields (website URL etc.)

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/shards#251]
When looking up information about a shard, it's important to know some key locations like where you can get more information and where it is hosted.
This is currently not provided in `shard.yml`.

I propose to introduce fields for informational URLs to relevant locations such as the website, repository, API docs, issue tracker etc.
Users could simply ad-hoc custom fields for this, but it would be beneficial to have a standardized format for extracting such information automatically. The `shards` command itself would not need to process them (except for display at some point).

Similar examples: Rubygems has `homepage` and [`metadata`](https://guides.rubygems.org/specification-reference/#metadata) fields. The latter accepts a mapping of custom descriptions to URLs. [Cargo](https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata) has `documentation`, `homepage` and `repository` fields. [NPM](https://docs.npmjs.com/files/package.json) has `homepage` and `repository` (holds a mapping similar to shards' dependencies).

I think the key references are to a website about the shard (usually called `homepage`) and the repository (`repository`).
These should probably simply be added as top level fields in the shards.yml specification.
I'd also consider links to a web presentation of the documentation and an issue tracker as important.  But perhaps these might added in a `metadata` field similar to Rubygems' where authors could also add custom mappings.

**Comment by RX14** [comment]
In what case would you have a shard but not the location of it's repository? Website is good though.

**Comment by Sija** [comment]
@RX14 with `path` resolver for instance.

**Comment by RX14** [comment]
Ok but that's only used in dev

**Comment by Sija** [comment]
That's probably 99% of the use cases, yes.

**Comment by straight-shoota** [comment]
The repository field also helps with mirrors and development forks. When someone forks a repo in order to contribute to the original one, this fork is not really a separate shard.
The `repository` URL simply points to the canonical repo.

When there is an intention to create a permanent fork, you'd simply change the `repository` field to your location.

**Comment by ysbaddaden** [comment]
We can probably have `documentation`, `homepage` and `repository` at the top level.

**Comment by straight-shoota** [comment]
`repository` should not be restricted to HTTP(S). A repository might as well be referenced by a `git` or `ssh` scheme.

Using a mapping like when specifying dependencies could also be considered. It's the same concept so this would line up nicely, although being mostly for convenience (probably).

```yaml
repository:
  github: crystal-lang/shards
```

**Comment by ysbaddaden** [comment]
I'm not fond of using a mapping. This is metadata, and I prefer them to be simple links, thus SHOULD preferably be HTTP so they can be linked from a shards index website, or quickly copy/pasted to a browser, yet still allow a valid VCS scheme (GIT, SSH).
