### ISSUE TITLE
Add --local to use the local cache as is (no git fetch)

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/shards#252]
Sometimes we don't want or need to update the local cache, and the numerous `git fetch` can be quite long. We could provide a `--local` command line argument (similar to ruby's bundler) to never update the local cache.

Obviously, if won't find new releases and commands can fail (e.g. the local cache doesn't exist), but it's still useful, when we know the cache is up-to-date (or up-to-date enough).

**Comment by RX14** [comment]
Also useful for when you're offline :)
