### ISSUE TITLE
[Feature] Add support for scripts

### ISSUE THREAD

**Issue by xquelard** [crystal-lang/shards#264]
Beginner in crystal, coming from javascript (node especially), in package.json, you can define scripts than you can run afterwards with "npm run name_of_user_created_script".

Maybe this could be useful as well in the shards.yml ? defining scripts and then "shards run ...".
I can try to add make the pull request for that feature to train on Crystal if you're interested, but I might need a bit of help :)

**Comment by z64** [comment]
I don't think this is entirely a concern for `shards`, which is primarily zeroed in on package development and management, and not so much end-users.

I think what you are looking for is analogous to something like `Rake` from Ruby, where a lot of Crystal's users come from. With respect to this, there are several Rake-like tools and libraries in the Crystal ecosystem you can take a look at and see if they suit your needs already:

https://github.com/axvm/cake
https://github.com/imdrasil/sam.cr
https://github.com/tbrand/neph

Aside, you could use the [`post-install`](https://github.com/crystal-lang/shards/blob/master/SPEC.md#postinstall) or [`executables`](https://github.com/crystal-lang/shards/blob/master/SPEC.md#executables) section of your `shard.yml` to make certain scripts or binaries available to the host after installing.

**Comment by ysbaddaden** [comment]
The only supported script is the postinstall hook to execute a command when the dependency is installed or updated, for example build an external library or an executable.

Arbitrary scripts are unlikely to be implemented. A simple Makefile is much more useful and flexible than npm-like scripts.

**Comment by straight-shoota** [comment]
@xquelard What would be the benefit of running `npm run name_of_user_created_script` vs.  `./scripts/name_of_user_created_script`?

**Comment by xquelard** [comment]
I'll just close the issue :)
