### ISSUE TITLE
Failed BuildCommandTest

### ISSUE THREAD

**Issue by j8r** [crystal-lang/shards#274]
mps point out on Gitter/IRC this failed test when running `make test` for shards 0.8.1 on Alpine edge with Crystal 0.28.0.
```
  1) Failure:
BuildCommandTest#test_reports_error_when_target_failed_to_compile [test/integration/build_test.cr:66]:
Expected FailedCommand but nothing was raised
```
I reproduced it with Crystal 0.28.0 for shards 0.8.1 and master on another Linux.

**Comment by ysbaddaden** [comment]
Already fixed in 25f06615a1819d9678114869e48d900d5e918f73
