### ISSUE TITLE
Support `.yaml` file extension

### ISSUE THREAD

**Issue by AlexWayfer** [crystal-lang/shards#279]
Hello!

I want to use `.yaml` file extension (`shard.yaml`): https://yaml.org/faq.html

But I'm getting the error:

```
Missing shard.yml. Please run 'shards init'
```

**Comment by ysbaddaden** [comment]
Sorry, the spec file name is `shard.yml`. Adding support for both extensions would only make things more complex and confusing.

**Comment by jgillich** [comment]
> Adding support for both extensions would only make things more complex and confusing.

`yaml` is the official Yaml extension though. I've never come across another tool that supports `yml` but not `yaml`, usually they support both. For for me the current behavior is more confusing, I default to using `yaml` always.

**Comment by straight-shoota** [comment]
I suppose `shard.yaml` would be better. I'd pick that if we'd be starting from scratch. But we're not.
It really doesn't matter much, though. It's just an agreed-upon name. The specification declares it's `shard.yml` and that works. You can't chose any different, neither the base name nor the extension.
Adding variability (or even changing the name entirely) doesn't add real value. It would only serve subjective preferences, but in the process adds unnecessary complexity and might cause confusion.
I think it's much better to keep it simple. Even with a name that might not be optimal.
