### ISSUE TITLE
Command to list dependencies

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/shards#292]
Is there a way show the dependency graph?  Something like `bundle viz` in console form?

If not `shard dependencies`, `shard show -v`, `shard show --deps` or `shard show deps` may be appropriate names.  Optional YAML output would be nice for use with other tools such as visualization or vulnerability scanners.

**Comment by straight-shoota** [comment]
Is `shards list --tree` good enough?

**Comment by didactic-drunk** [comment]
I think I confused `show` with `list`.  The names were only ideas.

**Comment by straight-shoota** [comment]
I mean the actually existing feature when you run `shards list --tree`. Does this work for you or do you need something else.

**Comment by ysbaddaden** [comment]
Yes there is `shards list` and `shards list -tree`.

**Comment by didactic-drunk** [comment]
Yes it's acceptable.  I guess 0.9.x was needed which Homebrew doesn't have.
