### ISSUE TITLE
-D flag not passed to crystal build

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/shards#307]
Basically using a -D flag when calling shards won't work.

**Comment by straight-shoota** [comment]
Why closed?

**Comment by bararchy** [comment]
I don't think it was `shards` fault and more a shell thing :) we used `shards build -p -- --release --no-debug --error-trace --warnings=all --error-on-warnings -Dpreview_mt`  where the extra `--` breaks the passing of the flag, without them it works as intended.
