### ISSUE TITLE
Opening in an editor?

### ISSUE THREAD

**Issue by atomical** [crystal-lang/shards#311]
Is there a way to open the libraries in an editor? In Ruby it's `bundle show gem_name`

**Comment by straight-shoota** [comment]
Such a tool doesn't exist (yet).

In contrast to bundler, shards always installs all dependencies in a local path at `lib/#{dependency_name}`. So there is really no need for any specific information that would be provided by `shards`. You can just implement this as a simple shell alias.

**Comment by z64** [comment]
While a simple case, #202 feels relevant here to help fill small gaps like these.

**Comment by ysbaddaden** [comment]
@straight-shoota said it all: dependencies are always installed under lib, so `shards show foo` will always be `./lib/foo`. I think just opening the lib folder is faster and simpler.
