### ISSUE TITLE
Unify shard names

### ISSUE THREAD

**Issue by acoolstraw** [crystal-lang/shards#312]
It's a bit of an annoyance keeping up with all the names for shards - the yml file is `shard`, the command for installing shards is `shards` and to create a shard using `crystal init` you have to type lib. Would be more uniform if they were all called the same thing.

**Comment by Blacksmoke16** [comment]
FWIW `shards init` is also a thing that just initializes a new `shard.yml`; `crystal init` is used to scaffold a whole Crystal project.

**Comment by acoolstraw** [comment]
When you're making a shard, you do use `crystal init lib` right?

**Comment by Blacksmoke16** [comment]
Yes, but the point I was trying to make is `crystal init` is outside the scope of this repo, and arguably should be its own thing.  Regardless there are only like 3 things here, hardly anything that is worth changing.

**Comment by straight-shoota** [comment]
I think it's quite simple to tell apart: 

* Shards is the program
* shard.yml is a shard's configuration file

The argument to `crystal init` isn't even related to that. `lib` just means your shard is supposed to be a library in contrast to an application. Both generate a shard.yml.

**Comment by acoolstraw** [comment]
I guess you have a point
