### ISSUE TITLE
 Doesn't seem to support versions like 1.0.0-beta1?

### ISSUE THREAD

**Issue by Nicolab** [crystal-lang/shards#318]
Hello,

I encountered `Error resolving validator (1.0.0-beta1)`

I have a doubt because: ` we parse 0.0.1-alpha as 0.0.1.pre.alpha but don't transform 0.0.1.beta` in:
https://github.com/crystal-lang/shards/pull/249#pullrequestreview-190628893

**Comment by ysbaddaden** [comment]
This was a mere comment and was never implemented. Any segment containing a letter indicates a prerelease. So `1.0.0-beta1` is identical to `1.0.0.beta1` and is a prerelease, but `0.1.0` or `1.2.3-4` are releases.

Either `validator` doesn't have a `1.0.0-beta1` release or you're running Shards 0.8 that doesn't support prereleases, and/or have a conflict.

**Comment by Nicolab** [comment]
Indeed, I'm running Shards 0.8.1
