### ISSUE TITLE
Index out of bounds error in `shards outdated`

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/shards#325]
Running `bin/shards outdated` on shards repo (master at 38b3d21f) raises `Index out of bounds` exception:
```console
$ bin/shards outdated
Resolving dependencies
Fetching https://github.com/crystal-lang/crystal-molinillo.git
Fetching https://github.com/ysbaddaden/minitest.cr.git
Unhandled exception: Index out of bounds (IndexError)
  from /usr/share/crystal/src/indexable.cr:0:13 in 'first'
  from src/commands/outdated.cr:47:9 in 'analyze'
  from src/commands/outdated.cr:20:35 in 'run'
  from src/commands/command.cr:27:7 in 'run:prereleases'
  from src/cli.cr:61:11 in '->'
  from /usr/share/crystal/src/option_parser.cr:255:3 in 'parse'
  from /usr/share/crystal/src/option_parser.cr:185:5 in 'parse'
  from src/cli.cr:58:5 in 'run'
  from src/cli.cr:108:3 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
$ bin/shards --version
Shards 0.9.0 [38b3d21] (2020-02-13)
```

**Comment by ysbaddaden** [comment]
It happens because the molinillo shard doesn't have any tagged release, but we expect one to exist.

**Comment by straight-shoota** [comment]
I just offloaded the issue and didn't look into it. But I can give it a try to fix this.

**Comment by ysbaddaden** [comment]
I think the command needs a little more love (and formal specification).

It's not trivial to fix because it involves a mutable refs (branch). There is no tagged version so we default to `branch: master`. Whenever a `branch` is defined, we should look whether the branch has new commits, and trigger the current/outdated, but... that's specific to the Git resolver.

**Comment by straight-shoota** [comment]
> Whenever a branch is defined, we should look whether the branch has new commits, and trigger the current/outdated

I'm not sure if that can work. Technically, a branch itself doesn't contain any information about whether one instance is newer than another. Such a relation can be constructed from the commit history if one commit is the parent of the other. But when neither commit history descends from the other branch state, there's no way to tell which one's newer. This is probably not that uncommon, because a branch is typically used to use a feature that's still worked on, which may include rebasing and force push.

The only thing that can be said with certainty is whether the branch points at a different commit. Maybe that should always trigger "outdated" or maybe branch dependencies should never be in that list at all?

**Comment by ysbaddaden** [comment]
Yes. As long as the locked commit isn't the current commit pointed to by the branch on the repository, then the shard is outdated. Whatever if commits were added or removed to the branch, or that it was rebased or deleted and rewritten from scratch: if the branch changed remotely, then the installed shard is out-of-sync, hence outdated.
