### ISSUE TITLE
Scripts don’t work on systems without /bin/sh

### ISSUE THREAD

**Issue by KimBurgess** [crystal-lang/shards#332]
Both [scripts](https://github.com/crystal-lang/shards/blob/1c648e596ec4e6f2f91204d64bb0d4d61a97e7b2/src/script.cr#L9) and the [resolver](https://github.com/crystal-lang/shards/blob/38b3d21f556981d30c94b9ff7f7ba8182c16089c/src/resolvers/git.cr#L309) current rely on `/bin/sh` existing, which is not always the case on some distros (e.g. NixOS).

Thoughts on switching this out for `/usr/bin/env bash`? This should help improve portability, and also ensure that it’s bash that ends up running (which is likely assumed), rather than an alt system shell.

**Comment by jhass** [comment]
Can you point out the standards that define `/bin/sh`and `/usr/bin/env`?  It seems weird that a system would implement the first but not the second, in fact I would expect it the other way around.

**Comment by KimBurgess** [comment]
I’m not aware of anything formal that defines the existent of `/usr/bin/env`, but the [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/sh.html) does explicitly note the lack of guaranteed existence of `/bin/sh`: 

> Applications should note that the standard PATH to the shell cannot be assumed to be either /bin/sh or /usr/bin/sh, and should be determined by interrogation of the PATH returned by getconf PATH, ensuring that the returned pathname is an absolute pathname and not a shell built-in.

**Comment by straight-shoota** [comment]
`/usr/bin/env bash` is definitely less portable than `/bin/sh` because it expects a specific shell implementation (bash), not just any shell.

@KimBurgess Do you have any insight how other applications implement for example compatibility with nixOS?

I suppose we could try to indentify which shell is available by testing `/bin/sh/`, `/usr/bin/env` and maybe other common paths and `$SHELL`. But I'd really appreciate if there is some already established behaviour we can follow.

The non-existance of `/bin/shell` is also a problem for stdlib's `Process.run(shell: true)`.

**Comment by j8r** [comment]
Have you an example to illustrate? NixOS does not work as now with `#!/bin/sh`? As far as I know, it has a symlink.

**Comment by KimBurgess** [comment]
Completely ignore everything I said. In my tired state last night, the issue I hit was due to `/bin/bash` being non-existent, but my brain saw this as `/bin/sh` and went off on a tangent. All working as intended.

As @j8r mentioned - `/bin/sh` _is_ symlinked and safe for use.

@straight-shoota - unless I’m missing something `Process.run` [looks to use `/bin/sh`](https://github.com/crystal-lang/crystal/blob/41bd18fbea4aec50aad33aa3beb7a0bf30544186/src/process.cr#L408) too. Although, I’m assuming that’s what you meant.

**Comment by straight-shoota** [comment]
Oh, well. Hope you've had a good night's sleep at least =)

That's what I meant. Regarding `Process.run` we could consider alternatives for when `/bin/sh` is not available. That's super low priority though.
