### ISSUE TITLE
Add small check for bad shards

### ISSUE THREAD

**Issue by hugopl** [crystal-lang/shards#350]
If a shard has a git tag like `v1.2.1`, but the shards.yml in the repository says `1.2.0`, `shards build` will always tell you to run `shards update` and you will end up blamming shards until notice it was a problem with the shard you were trying to use.

For sure this isn't a problem in shards itself, but such check is easy and a better message to the user would help a lot.

Not first time I ran into this "problem", a good error message would had saved some minutes.

**Comment by RX14** [comment]
Already solved by #341.
