### ISSUE TITLE
Malware detection/notification

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/shards#357]
Perhaps it's time to plan for supply chain attacks before crystal is targetted.

[https://www.zdnet.com/article/clipboard-hijacking-malware-found-in-725-ruby-libraries/](https://www.zdnet.com/article/clipboard-hijacking-malware-found-in-725-ruby-libraries/)
[https://blog.reversinglabs.com/blog/mining-for-malicious-ruby-gems](https://blog.reversinglabs.com/blog/mining-for-malicious-ruby-gems)

**Comment by Sija** [comment]
FWIW, shard releases based on git tags are a seriously weak point, since any1 can re-tag them at any given moment.

**Comment by jhass** [comment]
I'm not sure what you expect the action points to be here. If you have any, opening a separate issue per concrete suggestion seems to be more productive.

**Comment by j8r** [comment]
[This isse](https://github.com/crystal-lang/shards/issues/242) will limit a type of attacks, by pinning the commit hash along with the version.

**Comment by asterite** [comment]
Yes, please detail an action plan, otherwise there's no point in keeping this issue open.

**Comment by didactic-drunk** [comment]
I have.  It was shot down.  Where exactly can we discuss what action plan(s) would be acceptable without me writing multiple detailed plans that are all rejected?

**Comment by straight-shoota** [comment]
An open discussion without any actionable plans is best suited for the forum. As soon as some ideas are born they can be turned into an issue here.

**Comment by didactic-drunk** [comment]
@jhass I've seen other people on crystal-lang/crystal keep updating a list of action point items in a single issue which is what I intended here.  It doesn't matter as the forum post is up.

**Comment by straight-shoota** [comment]
The difference: This issue does not have a list of action point items.

**Comment by didactic-drunk** [comment]
@straight-shoota I didn't want to propose any as my proposals seem to gather opposition.  There is a list now.

**Comment by asterite** [comment]
So this is something to do on thr shards side, right? If that's the case, there's no need to discuss it in this repo.

**Comment by straight-shoota** [comment]
"Topics for discussion" are not actionable items in this repo. The only actionable item is #242 and we don't need a tracking list to track a single issue.
Let's continue this topic at https://forum.crystal-lang.org/t/malware-detection-notification/1971
