### ISSUE TITLE
Getting "Maybe a commit, branch or file doesn't exist?" error

### ISSUE THREAD

**Issue by thelinuxlich** [crystal-lang/shards#409]
Crystal: 0.35.0
Shards: 0.11.0

Trying to install crystal-community/zeromq-crystal gives me this error

**Comment by straight-shoota** [comment]
Can you be more specific? How do you install that shard?
Please share relevant configuration and commands to reproduce this error.

**Comment by thelinuxlich** [comment]
Actually I just found out the error only happens if I'm using a mounted Windows folder(running Crystal through WSL 2 on VSCode)

**Comment by straight-shoota** [comment]
Could you still share how to reproduce this (with WSL2)?

**Comment by thelinuxlich** [comment]
Steps for reproduction: On Windows 10, install any Linux distribution through the Microsoft Store, enable WSL 2(must be on a recent Windows 10 Insider Build), boot up the distribution through WSL, install Crystal, go to /mnt/c/some_folder(it's your mounted NTFS folder) create a new project with `crystal init app name`, add any github dependency to `shard.yml` and run `shards install`

**Comment by straight-shoota** [comment]
I can't reproduce this. Which Insider Build are you on? It's unlikely to be specific to the build, though.

It would really help if you would provide a concrete `shard.yml` file and the full error output from `shards install`.

**Comment by Blacksmoke16** [comment]
Maybe also with the `--verbose` flag ^?

**Comment by thelinuxlich** [comment]
I don't know what happened, now I'm able to run it flawlessly! It may be a issue regarding mounted NTFS disks, but somehow it's not happenning .anymore
