### ISSUE TITLE
Error when using SHARDS_OVERRIDE

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#432]
If you have an override file that you want to commit to your repo, but you don't always need it to contain info, you might just comment out stuff to start. This causes this error:

```
❯ SHARDS_OVERRIDE=shard.override.yml shards install
Resolving dependencies
Error in shard.override.yml: Expected DOCUMENT_START but was STREAM_END at line 7, column 1

  5. #     github: luckyframework/lucky
  6. #     branch: master
  7.
     ^
```

Where my file is formatted like this:

```yml
# Uncomment if you need to override
# dependencies:
#   lucky:
#     github: luckyframework/lucky
#     branch: master
```

oh... actually just to double check, I tested with a blank file, and that doesn't work either

```
❯ SHARDS_OVERRIDE=shard.override.yml shards install
Resolving dependencies
Error in shard.override.yml: Expected DOCUMENT_START but was STREAM_END at line 1, column 1

  1.
     ^
```

**Comment by bcardiff** [comment]
Yup, agree. It's a side effect of how empty documents are interpreted. 

A workaround that should work is to have dependencies key always present.
Or use another filename `shard.override-template.yml` (?) .

**Comment by jwoertink** [comment]
Yeah, if I just make it contain the same version the main one does, it works as a workaround. I might try to see if I can get github actions to not export SHARDS_OVERRIDE if the file is empty or missing or something 😅

**Comment by bcardiff** [comment]
You can use the following as a placeholder. Not great, though.

```yaml
dependencies: {}
# Uncomment if you need to override
# dependencies:
#   lucky:
#     github: luckyframework/lucky
#     branch: master
```

**Comment by jwoertink** [comment]
Ah, ok. Yeah, I was trying a few different combos that weren't working, but that's good to know. Thanks!
