### ISSUE TITLE
Support installing shards on Windows

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/shards#439]
* [ ] [Use git's `checkout` feature directly to write out repo files](https://github.com/crystal-lang/shards/pull/435)
* [x] [Don't use POSIX-specific shell constructs](https://github.com/crystal-lang/shards/pull/436)
* [x] [Use Process.quote instead of the old platform-specific helper](https://github.com/crystal-lang/shards/pull/437)
* [x] [Don't use compile-time shell commands to determine build timestamp](https://github.com/crystal-lang/shards/pull/438)
* [x] [Windows: pass a flag to allow creating symlinks without admin rights ](https://github.com/crystal-lang/crystal/pull/9767)

**Comment by Sija** [comment]
This ain't closed, yet.

**Comment by oprypin** [comment]
And, for a big finale..!

* [ ] [Add continuous testing (including Windows) using GitHub Actions](https://github.com/crystal-lang/shards/pull/448)
* [ ] [Expand Windows support + fix all specs](https://github.com/crystal-lang/shards/pull/447)
   * [ ] (offshoot) [Make rm_r able to delete read-only files on Windows](https://github.com/crystal-lang/crystal/pull/9903)

(no need to reopen this, shards installation technically already works)
