### ISSUE TITLE
Suggestion for new --silent flag

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/shards#499]
It would be neat if there was an additional `--silent` flag that could be used with `shards install` or `shards update` to not print anything out.

**Comment by Blacksmoke16** [comment]
Is `-q, --quiet                      Decrease the log verbosity, printing only warnings and errors.` not enough?

**Comment by jwoertink** [comment]
oh. Yeah, that's what I was looking for. I guess I missed it. Thanks
