### ISSUE TITLE
RFC: Shards Edit (add, rm, upgrade) commands

### ISSUE THREAD

**Issue by naqvis** [crystal-lang/shards#504]
Using this issue to start discussing the addition of **edit commands** to shards CLI. These commands will allow one to **add**, **remove**, and **upgrade** dependencies by modifying your `shard.yml` file from the command line.

Rust has something similar named `cargo-edit`.

Any thoughts?

**Comment by straight-shoota** [comment]
This proposal is already tracked in #144 including a discussion about the challenges with this approach.

**Comment by naqvis** [comment]
Thank you straight-shoota. Sorry wasn't aware of existing issue on the same. So I'll have it closed now.
