### ISSUE TITLE
Checking if crystal version satisfies current shard.yml

### ISSUE THREAD

**Issue by szabgab** [crystal-lang/shards#511]
I have a shard in which I edited the shard.yml and put
```
crystal: ">= 1.34.0"
```
Then ran `shards check` and it did not report any issues even though my current version of crystal does not satisfy the required version. Shouldn't shards verify that too?

**Comment by straight-shoota** [comment]
`shards check` is for dependencies. Users run it, if they want to make sure if all dependencies are installed. The  `crystal` property of the shard you're working on, doesn't matter for that.

I think these kind of validations should go into `shards validate` (#29). That would be run by the developer of a shard to make sure that it's good.

**Comment by beta-ziliani** [comment]
I'm closing this issue. @szabgab if you find the documentation can use some help to understand what `check` does, issue a specific ticket or PR. Thanks!
