### ISSUE TITLE
New command: outdated

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/shards#56]
The command shall list the outdated shards (and only them) along with the installed version, the available version (matching the requirements) and the latest version.

```
$ shards outdated
pg (0.3.0, available: 0.3.2, latest: 0.4.0)
minitest (0.1.3, available: 0.1.5)
```

**Comment by ysbaddaden** [comment]
refs #55

**Comment by marceloboeira** [comment]
@ysbaddaden are you guys currently assigning issues? I would certainly like to give it a shot on this.

**Comment by ysbaddaden** [comment]
Please go ahead!

**Comment by marceloboeira** [comment]
@ysbaddaden alright, already working on it :+1:

**Comment by ysbaddaden** [comment]
Optionally with a `--pre` command line argument to enable prereleases.
