### ISSUE TITLE
Move the repository to the crystal-lang organization? :-)

### ISSUE THREAD

**Issue by asterite** [crystal-lang/shards#91]
I'm not sure how to do it. Maybe you need to give me owner access to this repo, then I can transfer it.

**Comment by ysbaddaden** [comment]
I added you as a collaborator, but I don't think you'll be capable to transfer. I Can't transfer to `crystal-lang` myself because I don't have admin rights. Maybe transfer ownership to you, then you may transfer to the organisation? Or give me temporary admin rights, so I can transfer directly?

**Comment by asterite** [comment]
@ysbaddaden Done, you should now be able to transfer it

**Comment by ysbaddaden** [comment]
Transfered :smiley:
