### ISSUE TITLE
Compiling shards 0.6.1 on debian 8 [crystal 0.12]

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/shards#92]
Hi,

Interested by `crystal`, I want to bouild it from source.
I have installed `libedit-dev` `llvm` on my fresh debian 8 system.
After a successful `crystal` build
~~~sh
cd ~
git clone https://github.com/crystal-lang/crystal
cd crystal
git checkout 0.12.0
make
~~~
I ran
~~~sh
cd ~
git clone https://github.com/crystal-lang/shards
cd shards
git checkout v0.6.1
~/crystal/.build/crystal build src/shards.cr
~~~
:warning: I have installed `libevent-dev` `libgc-dev` :warning:
For `shards` building I have 
~~~sh
./.crystal/home/waghanza/crystal/src/ecr/process.cr/_main.o: In function `__crystal_main':
main_module:(.text+0x1b06): undefined reference to `GC_get_push_other_roots'
main_module:(.text+0x1b24): undefined reference to `GC_set_push_other_roots'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/home/waghanza/shards/.crystal/crystal-run-macro-run-_home_waghanza_crystal_src_ecr_process.cr.tmp" "${@}"  -rdynamic  /home/waghanza/crystal/src/ext/libcrystal.a -levent -lrt -lpcre -lgc -lpthread -ldl`
~~~

Has everyone build on debian `8` ?

Regards,

**Comment by ysbaddaden** [comment]
Don't install the libgc and libgc-dev packages, Crystal requires the current master of boehm GC.

Remove the libgc packages then follow instructions on https://github.com/crystal-lang/crystal/wiki/All-required-libraries to recompile Crystal, and then you should be capable to compile Shards.

**Comment by waghanza** [comment]
thanks, I will take a look @ this

**Comment by ysbaddaden** [comment]
This is a common pitfall of building Crystal. You were capable to compile your own Crystal because the releases come with the required, and up-to-date, static libraries (eg: `libgc.a`). But then the newly compiled compiler eventually fails to compile software because it doesn't have the static libraries anymore.
