### ISSUE TITLE
Missing shard.yml. Please run 'shards install'

### ISSUE THREAD

**Issue by albertodotcom** [crystal-lang/shards#93]
Hi, I'm playing around with crystal.
I tried to initialise a repo and I got the above message when running `shards install`.
Would `Please run 'shards init'` be a more appropriate message?

I've seen that it is possible to create a new project by typing `crystal init TYPE NAME [DIR]` but the above error message seems misleading to me.

**Comment by ysbaddaden** [comment]
Indeed. This is much better!
