### ISSUE TITLE
Use perticular version of a libray

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/shards#94]
Hi,

Trying to use the version **0.9** of `kemal`, I have added
~~~yaml
kemal:
    github: sdogruyol/kemal
    version: ~> 0.9
~~~
on my `shards.yml`

Could I precise to `shard` the version I want to use, and rather only `X`.`Y` in `semver` ?

**Comment by jhass** [comment]
Sure, specifying the exact version without using `~>` should just work.

**Comment by waghanza** [comment]
so, I can use the syntax `-> X.Y` and the latest patch `Z` will be installed when I use `shards update` ?

**Comment by jhass** [comment]
https://github.com/crystal-lang/shards/blob/master/SPEC.md#version-1

**Comment by waghanza** [comment]
that what I say I use the synatax 
~~~yaml
  kemal:
    github: sdogruyol/kemal
    version: ~> 0.9
~~~
but the next version of `kemal` was installed
~~~crystal
Installing kemal (0.10.0)
~~~

**Comment by jhass** [comment]
`~> a.b` is `>= a.b && < a.b+1`, so you're looking for `~> 0.9.0`

**Comment by waghanza** [comment]
ah ok
in `Rails`, I use two digits to specify version in use

**Comment by ysbaddaden** [comment]
`~> 0.9` is understood as "anything in 0.x that is at minimum 0.9". I believe this is identical to Bundler. Am I wrong?

**Comment by waghanza** [comment]
For https://github.com/rails/web-console

* ~> 1.0 => leads me to 1.0.4 (the last version of 1.Y.Z)
* ~> 2.0 => leads me to 2.3.0 (the last version of 2.Y.Z)
* ~> 3.0 => leads me to 3.1.1 (the last version of 3.X.Z)


interesting, I always thought that specify only `X.Y` in the gemfile will use the latest `X` version, but seems to use the latest `Y` version, and protect you from **major** (`X`) changes
