### ISSUE TITLE
Broken symlink when adding a path dependency

### ISSUE THREAD

**Issue by soveran** [crystal-lang/shards#99]
I'd like to see if anyone can confirm this issue. The symlink is created from the root of the project, but it should be created from `./libs` instead (so that the path in the link is relative to the directory where the link will be created). The fix should be trivial (changing the working directory to `./libs` before creating the link).

**Comment by ysbaddaden** [comment]
Maybe we should always use an absolute path?

**Comment by soveran** [comment]
I think using relative paths in `shard.yml` has more potential for sharing it with project collaborators, whereas using absolute paths leaves that option out. I have a fix that works, but it requires the paths to be declared relative to `INSTALL_PATH` (instead of the project root) and it also requires the `INSTALL_PATH` directory to be created in order to read the dependency version (in the fix, I create that directory while running `read_spec`, which is a harmless but unexpected side effect).

**Comment by ysbaddaden** [comment]
I said the link should be absolute, not that the path configuration has to be absolute. It could be relative to the project root, expanded from there and eventually created as an absolute link.

This way we'd avoid both caveats: unexpected relative path, and always creating the install path even when not installing.

**Comment by soveran** [comment]
Gotcha, yes, it makes perfect sense :-)

```diff
-      src_path = File.join(local_path, "src")
+      src_path = File.expand_path(File.join(local_path, "src"))
```

**Comment by ysbaddaden** [comment]
Looks good! Can you write an integration test and open a pull request? Otherwise I'll have a look soon.

**Comment by soveran** [comment]
I'll give it a try tomorrow morning.
